In [66]:
pip install xgboost

In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [68]:
pip install catboost

In [69]:
from catboost import CatBoostClassifier

In [70]:
# Load the data
dataset = pd.read_csv('/content/indian_liver_patient.csv')

In [71]:
# Separate features and target variable
X=dataset.iloc[:, :-2].values#independet variable matrix
y=dataset.iloc[:, -1].values#dependent variable vector

In [72]:
dataset.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [73]:
#Handling missing data
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(X[:,2:11])
X[:,2:11]=imputer.transform(X[:,2:11])

# importing packages
import seaborn
import matplotlib.pyplot as plt

#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],remainder='passthrough')
X = ct.fit_transform(X)

labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [74]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [75]:
# Train and evaluate AdaboostClassifier
clf_adaboost = AdaBoostClassifier()
clf_adaboost.fit(X_train, y_train)
y_pred_adaboost = clf_adaboost.predict(X_test)

In [76]:
accuracy_adaboost = accuracy_score(y_test, y_pred_adaboost)
print('AdaboostClassifier accuracy:', accuracy_adaboost)

AdaboostClassifier accuracy: 0.7435897435897436


In [77]:
# Train and evaluate GradientBoostingClassifier
clf_gradientboosting = GradientBoostingClassifier()
clf_gradientboosting.fit(X_train, y_train)
y_pred_gradientboosting = clf_gradientboosting.predict(X_test)

In [78]:
accuracy_gradientboosting = accuracy_score(y_test, y_pred_gradientboosting)
print('GradientBoostingClassifier accuracy:', accuracy_gradientboosting)

GradientBoostingClassifier accuracy: 0.7350427350427351


In [79]:
import xgboost as xg
xgb_regressor = xgb.XGBRegressor()

In [80]:
# Train and evaluate XGBoostClassifier
clf_xg = XGBClassifier()
clf_xg.fit(X_train, y_train)
y_pred_xg = clf_xg.predict(X_test)

accuracy_xg = accuracy_score(y_test, y_pred_xg)
print('XGBoostClassifier accuracy:', accuracy_xg)



XGBoostClassifier accuracy: 0.7264957264957265


In [81]:
# Train and evaluate CatBoostClassifier
clf_catboost = CatBoostClassifier()
clf_catboost.fit(X_train, y_train)
y_pred_catboost = clf_catboost.predict(X_test)

accuracy_catboost = accuracy_score(y_test, y_pred_catboost)
print('CatBoostClassifier accuracy:', accuracy_catboost)

Learning rate set to 0.007436
0:	learn: 0.6896863	total: 48.6ms	remaining: 48.6s
1:	learn: 0.6868507	total: 50.4ms	remaining: 25.2s
2:	learn: 0.6838268	total: 52.4ms	remaining: 17.4s
3:	learn: 0.6807765	total: 55ms	remaining: 13.7s
4:	learn: 0.6779302	total: 58ms	remaining: 11.5s
5:	learn: 0.6753988	total: 59.8ms	remaining: 9.9s
6:	learn: 0.6722858	total: 61.8ms	remaining: 8.76s
7:	learn: 0.6695351	total: 63.6ms	remaining: 7.89s
8:	learn: 0.6666703	total: 65.3ms	remaining: 7.2s
9:	learn: 0.6635120	total: 67.1ms	remaining: 6.64s
10:	learn: 0.6609467	total: 70.1ms	remaining: 6.3s
11:	learn: 0.6582506	total: 72.5ms	remaining: 5.97s
12:	learn: 0.6559684	total: 73.9ms	remaining: 5.61s
13:	learn: 0.6533492	total: 75.3ms	remaining: 5.31s
14:	learn: 0.6509591	total: 76.8ms	remaining: 5.04s
15:	learn: 0.6485953	total: 78.2ms	remaining: 4.81s
16:	learn: 0.6462889	total: 79.7ms	remaining: 4.61s
17:	learn: 0.6435927	total: 81.2ms	remaining: 4.43s
18:	learn: 0.6412633	total: 82.6ms	remaining: 4.26s

In [82]:
# Confusion matrix for each model
print('\nConfusion Matrix for AdaboostClassifier:')
print(confusion_matrix(y_test, y_pred_adaboost))

print('\nConfusion Matrix for GradientBoostingClassifier:')
print(confusion_matrix(y_test, y_pred_gradientboosting))

print('\nConfusion Matrix for XGBoostClassifier:')
print(confusion_matrix(y_test, y_pred_xg))


print('\nConfusion Matrix for CatBoostClassifier:')
print(confusion_matrix(y_test, y_pred_catboost))


















Confusion Matrix for AdaboostClassifier:
[[71 16]
 [14 16]]

Confusion Matrix for GradientBoostingClassifier:
[[74 13]
 [18 12]]

Confusion Matrix for XGBoostClassifier:
[[73 14]
 [18 12]]

Confusion Matrix for CatBoostClassifier:
[[77 10]
 [18 12]]
